language: android
android:
  components:
  - platform-tools,tools
  - extra-google-m2repository
  - build-tools-26.0.1
  - extra-google-google_play_services,addon-google_apis-google-24
  - android-21,android-22,android-23,android-24,android-25,android-26
  licenses:
  - android-sdk-preview-license-*
  - android-sdk-license-.+
  - google-gdk-license-.+
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -f  $HOME/.gradle/caches/modules-3/modules-3.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/"
  - "$HOME/.Android/"
jdk: oraclejdk8
deploy:
  provider: releases
  file_glob: true
  file:
  - ./*/build/outputs/apk/*
  - ./*/build/outputs/lint-results-*.*
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: 0ikMeKE58gx95n0TIvlH8MvysTpxBDQjYYaEiX2WaFmwdlWdYJ8r6YqsEI2H3WNMHYuodK7MEFtVc1/KVXdUXFU2bIm3JoRSikmKB2mwDfIKAFIBj8NY6YhkZZQIIelCraOVuGr5h0jHNEMvF9QBrVnCGDDCFWxGDiVZ59HzV7QCqLwmmOMuCCLB/UgvKATkxPBbxPe0IQ+Dx0CVTIhm81lrgNkXOCMU2SwlS2gi9pfEE7jKBqWH9yiA7rTMakEO9tFq2qp2FMBCRQELbIEzhIfF5RlWItYSRPM9gA96Ox1guJOJIXoqH7nr3y5Me2jKehMabiyOikHUmHGHF6S6Q1OVnspEHv3HKbIO/yciHT8fOOuCnPCvD8GNyQ6nDsGr8jdgfmdoAuYwnzbLqe+3oytj/Q2mIqAAKe8pURtlz9WaQVdSHgvxQBNwDkdokrs53uFxl4/Bqrxnx/o9eaKLEa2CUbOz1u1X6rrXYmbMXAOqCXrDEVJ02EtEJwnQbmTuzn6FtBDkEX1hHjRXT5rU0VsyfktAMYviX+E1/1/VL27qNf4s76GIuEUiqXQm+Iy25tFO6xRMXI5XcyCnMza0s4tHAxygwSVigRWl6RSiXgMzaTTLEtGeRQAYs7elwitFGlMYjCAgQgQjMBqweyLn2uj5sbDg/owrDv5VzNBau4g=
before_script: true
script:
- which adb
- "./gradlew clean build"
